# Generated by Django 4.2.4 on 2023-08-10 12:46

import cards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='id',
            field=cards.models.CustomAutoField(primary_key=True, serialize=False),
        ),
    ]
