# Generated by Django 4.2.4 on 2023-08-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_benefit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='mylist_count',
            field=models.IntegerField(default=0, verbose_name='담긴수'),
        ),
        migrations.AddField(
            model_name='card',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
